/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Lock l1 = new Lock();

        l1.setCode();
        l1.onTop();
        l1.lockStatus();
        l1.rightDirection();
        l1.leftDirection();
        l1.turnRightAgain();
        l1.isClosed();




    }// end main

}// end class
