/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test

    public void testAppHasAStatus() {
        App classUnderTest = new App();

    }
}
